org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:+IgnoreUnrecognizedVMOptions -XX:+UseG1GC
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
flutter.compileSdkVersion=34
flutter.minSdkVersion=20
flutter.targetSdkVersion=34
# Suppress AGP validation for Java 21 + compileSdk issue
android.disableResourceValidation=true
